name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Calculate Release Tag
      id: release-tag
      run: echo "release-tag=1.0.$(date +%s)" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: solenersync-userstore
        IMAGE_TAG: ${{ steps.release-tag.outputs.release-tag }}
      run: |
        aws ecr describe-repositories --repository-names ${REPOSITORY} || aws ecr create-repository --repository-name ${REPOSITORY}
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push -a $REGISTRY/$REPOSITORY

