name: Contract Tests

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://solenersync.pactflow.io
  PACT_BROKER_HOST: solenersync.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  test:
    name: Provider verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          overwrite-settings: false
      - name: Prepare
        run: mvn compile test-compile
      - name: Pull and verify contracts
        run: mvn test -P pact-provider -Dpactbroker.url=$PACT_BROKER_BASE_URL -Dpact.verifier.publishResults=true -Dpact.provider.version=$GIT_COMMIT -Dprovider.version.branch=${GIT_REF:11} -Dpactbroker.consumerversionselectors.branch=main