name: Provider Tests

on:
  repository_dispatch:
    types: [ pact_changed ]

env:
  PACT_BROKER_BASE_URL: https://solenersync.pactflow.io
  PACT_BROKER_HOST: solenersync.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  CONSUMER_VERSION_TAGS: ${{ github.event.client_payload.consumer_version_tags }}

jobs:
  test:
    name: On event dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          overwrite-settings: false
      - name: Prepare
        run: mvn compile test-compile
      - name: Pull and verify contracts
        run: mvn test -P pact-provider -Dpact.verifier.publishResults=true -Dpact.provider.version=${GITHUB_REF:11} -Dpactbroker.consumerversionselectors.tags=${CONSUMER_VERSION_TAGS}