name: Build

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://solenersync.pactflow.io
  PACT_BROKER_HOST: solenersync.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          overwrite-settings: false
      - name: Prepare
        run: mvn compile test-compile
      - name: Test
        run: GIT_BRANCH=${GITHUB_REF:11} make test

  # Runs on branches as well, so we know the status of our PRs
  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: GIT_BRANCH=${GITHUB_REF:11} make can_i_deploy
#
#  # Only deploy from master
#  deploy:
#    runs-on: ubuntu-latest
#    needs: can-i-deploy
#    steps:
#      - uses: actions/checkout@v2
#      - run: docker pull pactfoundation/pact-cli:latest
#      - name: Deploy
#        run: GIT_BRANCH=${GITHUB_REF:11} make deploy
#        if: github.ref == 'refs/heads/master'