name: Provider Tests

on:
  push:
    branches:
      - main

env:
  PACT_BROKER_BASE_URL: https://solenersync.pactflow.io
  PACT_BROKER_HOST: solenersync.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  GIT_REF: ${{github.event.number}}

jobs:
  test:
    name: Verify on push to main
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          overwrite-settings: false
      - name: Prepare
        run: mvn compile test-compile
      - name: Pull and verify contracts
        run: mvn test -P pact-provider -Dpact.verifier.publishResults=true -Dpact.provider.version=${GIT_REF:10}